// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ReceiveModel;
//
//    var receiveModel = ReceiveModel.FromJson(jsonString);

namespace ReceiveModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ReceiveModel
    {
        [JsonProperty("link")]
        public string Link { get; set; }
    }

    public partial class ReceiveModel
    {
        public static ReceiveModel FromJson(string json) => JsonConvert.DeserializeObject<ReceiveModel>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ReceiveModel self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
